/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lfwUtilsAvalancheSol from "./LFWUtils_Avalanche.sol";
export type { lfwUtilsAvalancheSol };
import type * as lfwUtilsBscSol from "./LFWUtils_BSC.sol";
export type { lfwUtilsBscSol };
import type * as lfwUtilsCronosSol from "./LFWUtils_Cronos.sol";
export type { lfwUtilsCronosSol };
import type * as lfwUtilsEthSol from "./LFWUtils_ETH.sol";
export type { lfwUtilsEthSol };
import type * as lfwUtilsFantomSol from "./LFWUtils_Fantom.sol";
export type { lfwUtilsFantomSol };
import type * as lfwUtilsPolygonSol from "./LFWUtils_Polygon.sol";
export type { lfwUtilsPolygonSol };
