/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ITectonicInterface,
  ITectonicInterfaceInterface,
} from "../../../contracts/LFWUtils_Cronos.sol/ITectonicInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "pendingTONIC",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ITectonicInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ITectonicInterfaceInterface {
    return new utils.Interface(_abi) as ITectonicInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ITectonicInterface {
    return new Contract(address, _abi, signerOrProvider) as ITectonicInterface;
  }
}
