/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IApeSwapFarmingInteface,
  IApeSwapFarmingIntefaceInterface,
} from "../../../contracts/LFWUtils_Polygon.sol/IApeSwapFarmingInteface";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pId",
        type: "uint256",
      },
    ],
    name: "lpToken",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "pendingBanana",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_pId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "userInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IApeSwapFarmingInteface__factory {
  static readonly abi = _abi;
  static createInterface(): IApeSwapFarmingIntefaceInterface {
    return new utils.Interface(_abi) as IApeSwapFarmingIntefaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IApeSwapFarmingInteface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IApeSwapFarmingInteface;
  }
}
