/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGNSStakingP2Interface,
  IGNSStakingP2InterfaceInterface,
} from "../../../contracts/LFWUtils_Polygon.sol/IGNSStakingP2Interface";

const _abi = [
  {
    inputs: [],
    name: "accDaiPerDai",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "users",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGNSStakingP2Interface__factory {
  static readonly abi = _abi;
  static createInterface(): IGNSStakingP2InterfaceInterface {
    return new utils.Interface(_abi) as IGNSStakingP2InterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGNSStakingP2Interface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IGNSStakingP2Interface;
  }
}
