/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISandboxUtils,
  ISandboxUtilsInterface,
} from "../../../contracts/LFWUtils_Polygon.sol/ISandboxUtils";

const _abi = [
  {
    inputs: [],
    name: "getRate",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISandboxUtils__factory {
  static readonly abi = _abi;
  static createInterface(): ISandboxUtilsInterface {
    return new utils.Interface(_abi) as ISandboxUtilsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISandboxUtils {
    return new Contract(address, _abi, signerOrProvider) as ISandboxUtils;
  }
}
