/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBenqiInterface } from "./IBenqiInterface";
export type { IGMXInterface } from "./IGMXInterface";
export type { IGMXStakingInterface } from "./IGMXStakingInterface";
export type { IJoeFarmingV1Interface } from "./IJoeFarmingV1Interface";
export type { IJoeFarmingV2Interface } from "./IJoeFarmingV2Interface";
export type { IJoeFarmingV3Interface } from "./IJoeFarmingV3Interface";
export type { IJoeStakingInterface } from "./IJoeStakingInterface";
export type { IPair } from "./IPair";
export type { IWonderlandInterface } from "./IWonderlandInterface";
export type { LFWUtils_Avalanche } from "./LFWUtils_Avalanche";
