/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ILidoOracleInterfaceInterface extends utils.Interface {
  functions: {
    "getLastCompletedReportDelta()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getLastCompletedReportDelta"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getLastCompletedReportDelta",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getLastCompletedReportDelta",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ILidoOracleInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ILidoOracleInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getLastCompletedReportDelta(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;
  };

  getLastCompletedReportDelta(
    overrides?: CallOverrides
  ): Promise<[BigNumber, BigNumber, BigNumber]>;

  callStatic: {
    getLastCompletedReportDelta(
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    getLastCompletedReportDelta(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getLastCompletedReportDelta(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
