/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IApeSwapFarmingInteface } from "./IApeSwapFarmingInteface";
export type { IGNSFarmingInterface } from "./IGNSFarmingInterface";
export type { IGNSStakingP1Interface } from "./IGNSStakingP1Interface";
export type { IGNSStakingP2Interface } from "./IGNSStakingP2Interface";
export type { IPair } from "./IPair";
export type { IQuickSwapDualLPFarmingInterface } from "./IQuickSwapDualLPFarmingInterface";
export type { IQuickSwapLPFarmingInterface } from "./IQuickSwapLPFarmingInterface";
export type { IQuickSwapStakingInterface } from "./IQuickSwapStakingInterface";
export type { ISandboxStakingInterface } from "./ISandboxStakingInterface";
export type { ISandboxUtils } from "./ISandboxUtils";
export type { ISushiswapFarmingInterface } from "./ISushiswapFarmingInterface";
export type { LFWUtils_Polygon } from "./LFWUtils_Polygon";
