/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IVenusVAIInterface,
  IVenusVAIInterfaceInterface,
} from "../../../contracts/LFWUtils_BSC.sol/IVenusVAIInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "pendingXVS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "userInfo",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IVenusVAIInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IVenusVAIInterfaceInterface {
    return new utils.Interface(_abi) as IVenusVAIInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IVenusVAIInterface {
    return new Contract(address, _abi, signerOrProvider) as IVenusVAIInterface;
  }
}
