/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ICronaFarmingInterface } from "./ICronaFarmingInterface";
export type { ICronaStakingInterface } from "./ICronaStakingInterface";
export type { IMMInterface } from "./IMMInterface";
export type { IPair } from "./IPair";
export type { ITectonicInterface } from "./ITectonicInterface";
export type { IVVSInterface } from "./IVVSInterface";
export type { LFWUtils_Cronos } from "./LFWUtils_Cronos";
