/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IFWalletInterface__factory } from "./IFWalletInterface__factory";
export { IGeistFarmingInterface__factory } from "./IGeistFarmingInterface__factory";
export { IGeistStakingInterface__factory } from "./IGeistStakingInterface__factory";
export { IPair__factory } from "./IPair__factory";
export { ISpiritInterface__factory } from "./ISpiritInterface__factory";
export { ISpookyFarmingInterface__factory } from "./ISpookyFarmingInterface__factory";
export { ISpookyStakingInterface__factory } from "./ISpookyStakingInterface__factory";
export { IWigoInterface__factory } from "./IWigoInterface__factory";
export { LFWUtils_Fantom__factory } from "./LFWUtils_Fantom__factory";
