/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IConvexEarncvxCRVInterface,
  IConvexEarncvxCRVInterfaceInterface,
} from "../../../contracts/LFWUtils_ETH.sol/IConvexEarncvxCRVInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "address",
        name: "_rewardToken",
        type: "address",
      },
    ],
    name: "rewards",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_pId",
        type: "uint256",
      },
    ],
    name: "userLocks",
    outputs: [
      {
        internalType: "uint112",
        name: "",
        type: "uint112",
      },
      {
        internalType: "uint112",
        name: "",
        type: "uint112",
      },
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IConvexEarncvxCRVInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IConvexEarncvxCRVInterfaceInterface {
    return new utils.Interface(_abi) as IConvexEarncvxCRVInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConvexEarncvxCRVInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IConvexEarncvxCRVInterface;
  }
}
