/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IConvexEarnCRVInterface,
  IConvexEarnCRVInterfaceInterface,
} from "../../../contracts/LFWUtils_ETH.sol/IConvexEarnCRVInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "earned",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IConvexEarnCRVInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IConvexEarnCRVInterfaceInterface {
    return new utils.Interface(_abi) as IConvexEarnCRVInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IConvexEarnCRVInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IConvexEarnCRVInterface;
  }
}
