/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ILidoOracleInterface,
  ILidoOracleInterfaceInterface,
} from "../../../contracts/LFWUtils_ETH.sol/ILidoOracleInterface";

const _abi = [
  {
    inputs: [],
    name: "getLastCompletedReportDelta",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ILidoOracleInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ILidoOracleInterfaceInterface {
    return new utils.Interface(_abi) as ILidoOracleInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ILidoOracleInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ILidoOracleInterface;
  }
}
