/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IShibaswapInterface,
  IShibaswapInterfaceInterface,
} from "../../../contracts/LFWUtils_ETH.sol/IShibaswapInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IShibaswapInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IShibaswapInterfaceInterface {
    return new utils.Interface(_abi) as IShibaswapInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IShibaswapInterface {
    return new Contract(address, _abi, signerOrProvider) as IShibaswapInterface;
  }
}
