/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  ISushiswapStakingInterface,
  ISushiswapStakingInterfaceInterface,
} from "../../../contracts/LFWUtils_ETH.sol/ISushiswapStakingInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ISushiswapStakingInterface__factory {
  static readonly abi = _abi;
  static createInterface(): ISushiswapStakingInterfaceInterface {
    return new utils.Interface(_abi) as ISushiswapStakingInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ISushiswapStakingInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ISushiswapStakingInterface;
  }
}
