/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBenqiInterface,
  IBenqiInterfaceInterface,
} from "../../../contracts/LFWUtils_Avalanche.sol/IBenqiInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "getPooledAvaxByShares",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IBenqiInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IBenqiInterfaceInterface {
    return new utils.Interface(_abi) as IBenqiInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBenqiInterface {
    return new Contract(address, _abi, signerOrProvider) as IBenqiInterface;
  }
}
