/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGMXInterface,
  IGMXInterfaceInterface,
} from "../../../contracts/LFWUtils_Avalanche.sol/IGMXInterface";

const _abi = [
  {
    inputs: [],
    name: "stakedGmxTracker",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGMXInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IGMXInterfaceInterface {
    return new utils.Interface(_abi) as IGMXInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGMXInterface {
    return new Contract(address, _abi, signerOrProvider) as IGMXInterface;
  }
}
