/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGMXStakingInterface,
  IGMXStakingInterfaceInterface,
} from "../../../contracts/LFWUtils_Avalanche.sol/IGMXStakingInterface";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "claimable",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_user",
        type: "address",
      },
    ],
    name: "stakedAmounts",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IGMXStakingInterface__factory {
  static readonly abi = _abi;
  static createInterface(): IGMXStakingInterfaceInterface {
    return new utils.Interface(_abi) as IGMXStakingInterfaceInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGMXStakingInterface {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IGMXStakingInterface;
  }
}
