/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface IFWalletInterfaceInterface extends utils.Interface {
  functions: {
    "getStake(address,uint256)": FunctionFragment;
    "lastValidatorID()": FunctionFragment;
    "pendingRewards(address,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "getStake" | "lastValidatorID" | "pendingRewards"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getStake",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "lastValidatorID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "pendingRewards",
    values: [PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "getStake", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lastValidatorID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingRewards",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IFWalletInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IFWalletInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getStake(
      _user: PromiseOrValue<string>,
      _vId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    lastValidatorID(overrides?: CallOverrides): Promise<[BigNumber]>;

    pendingRewards(
      _user: PromiseOrValue<string>,
      _vId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;
  };

  getStake(
    _user: PromiseOrValue<string>,
    _vId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  lastValidatorID(overrides?: CallOverrides): Promise<BigNumber>;

  pendingRewards(
    _user: PromiseOrValue<string>,
    _vId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  callStatic: {
    getStake(
      _user: PromiseOrValue<string>,
      _vId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastValidatorID(overrides?: CallOverrides): Promise<BigNumber>;

    pendingRewards(
      _user: PromiseOrValue<string>,
      _vId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    getStake(
      _user: PromiseOrValue<string>,
      _vId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    lastValidatorID(overrides?: CallOverrides): Promise<BigNumber>;

    pendingRewards(
      _user: PromiseOrValue<string>,
      _vId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getStake(
      _user: PromiseOrValue<string>,
      _vId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    lastValidatorID(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    pendingRewards(
      _user: PromiseOrValue<string>,
      _vId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
