/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IFWalletInterface } from "./IFWalletInterface";
export type { IGeistFarmingInterface } from "./IGeistFarmingInterface";
export type { IGeistStakingInterface } from "./IGeistStakingInterface";
export type { IPair } from "./IPair";
export type { ISpiritInterface } from "./ISpiritInterface";
export type { ISpookyFarmingInterface } from "./ISpookyFarmingInterface";
export type { ISpookyStakingInterface } from "./ISpookyStakingInterface";
export type { IWigoInterface } from "./IWigoInterface";
export type { LFWUtils_Fantom } from "./LFWUtils_Fantom";
